#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SANDBOX_ROOT="${CODEX_SANDBOX_ROOT:-$REPO_DIR/.sandbox}"
SANDBOX_APP_DIR="${CODEX_SANDBOX_APP_DIR:-$SANDBOX_ROOT/codex-app}"
SANDBOX_PROFILE_DIR="${CODEX_SANDBOX_PROFILE_DIR:-$SANDBOX_ROOT/profile}"
SANDBOX_RUNTIME_ROOT="${CODEX_SANDBOX_RUNTIME_ROOT:-$SANDBOX_PROFILE_DIR/runtime}"
SANDBOX_WEBVIEW_PORT="${CODEX_SANDBOX_WEBVIEW_PORT:-55175}"
SANDBOX_REMOTE_DEBUGGING_PORT="${CODEX_SANDBOX_REMOTE_DEBUGGING_PORT:-9223}"

export CODEX_REMOTE_APP_DIR="${CODEX_REMOTE_APP_DIR:-$SANDBOX_APP_DIR}"
export CODEX_REMOTE_STATE_ROOT="${CODEX_REMOTE_STATE_ROOT:-$SANDBOX_PROFILE_DIR}"
export CODEX_REMOTE_RUNTIME_ROOT="${CODEX_REMOTE_RUNTIME_ROOT:-$SANDBOX_RUNTIME_ROOT}"
export CODEX_REMOTE_PID_PREFIX="${CODEX_REMOTE_PID_PREFIX:-sandbox-remote}"
export CODEX_REMOTE_DEVICE_ID="${CODEX_REMOTE_DEVICE_ID:-sandbox-local}"
export CODEX_REMOTE_WEBVIEW_SOURCE="${CODEX_REMOTE_WEBVIEW_SOURCE:-$SANDBOX_APP_DIR/content/webview}"
export CODEX_REMOTE_WEBVIEW_ORIGIN="${CODEX_REMOTE_WEBVIEW_ORIGIN:-http://127.0.0.1:${SANDBOX_WEBVIEW_PORT}}"
export CODEX_REMOTE_CDP_ORIGIN="${CODEX_REMOTE_CDP_ORIGIN:-http://127.0.0.1:${SANDBOX_REMOTE_DEBUGGING_PORT}}"

exec "$SCRIPT_DIR/remote-supervisor.sh" "$@"
